"""
pptx_export.py — Management-grade PowerPoint export for FP&A Variance Copilot.

Produces a 6-slide management pack that looks like it was built by an FP&A team,
not generated by a script.  Every layout decision — spacing, font sizes, color
allocation — was made with a real presentation context in mind.

Slide structure
---------------
1. Title          — dark slate background, period + tone label, timestamp
2. Executive KPIs — 4 teal-accented card boxes on light background
3. Waterfall      — Plotly chart rendered to PNG, embedded full-width
4. Variances      — material items table, header in dark slate, alt row shading
5. Commentary     — cleaned text with left teal accent bar, tone in title
6. Forward Look   — projection table + risk narrative

Dependencies
------------
python-pptx  (layout + text)
kaleido      (chart → PNG — graceful fallback if missing)
"""

from __future__ import annotations

import re
from datetime import datetime
from io import BytesIO

import pandas as pd
from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches, Pt

from charts import plot_projection, plot_waterfall
from projection import next_quarter_label, project_next_quarter, summarize_projection
from variance_engine import get_material_items


# ── Slide dimensions ──────────────────────────────────────────────────────────

_W  = Inches(13.33)
_H  = Inches(7.5)

# Content area inside all slides (except title)
_ML = 0.55   # left margin, inches
_MR = 0.55   # right margin, inches
_CW = 13.33 - _ML - _MR   # content width: 12.23"
_CT = 1.10   # content top (below slide title area)
_CH = 7.5 - _CT - 0.25    # content height: 6.15"


# ── Color palette ─────────────────────────────────────────────────────────────

_C = {
    "dark":      "#0F172A",
    "s800":      "#1E293B",
    "s700":      "#334155",
    "s600":      "#475569",
    "s500":      "#64748B",
    "s400":      "#94A3B8",
    "s300":      "#CBD5E1",
    "s200":      "#E2E8F0",
    "s100":      "#F1F5F9",
    "s50":       "#F8FAFC",
    "teal":      "#0D9488",
    "teal_l":    "#5EEAD4",
    "white":     "#FFFFFF",
    "green":     "#16A34A",
    "red":       "#DC2626",
    "amber":     "#D97706",
}


# ── Public entry point ────────────────────────────────────────────────────────

def build_presentation(
    enriched_df: pd.DataFrame,
    cat_df: pd.DataFrame,
    waterfall_df: pd.DataFrame,
    period: str,
    tone: str,
    commentary: str | None = None,
    projection_df: pd.DataFrame | None = None,
    risk_narrative: str | None = None,
) -> BytesIO:
    """
    Assemble the full 6-slide management pack and return it as a BytesIO buffer.

    Parameters
    ----------
    enriched_df    : output of compute_variances()
    cat_df         : output of summarize_by_category()
    waterfall_df   : output of build_waterfall_data()
    period         : reporting period label, e.g. "Q4 2024"
    tone           : commentary tone ("Board Presentation" / "Internal Team Update" /
                     "Investor Call Prep")
    commentary     : commentary text to include on Slide 5; None = slide is still
                     rendered with a placeholder message
    projection_df  : output of project_next_quarter(); if None, computed with
                     default parameters (0% budget growth)
    risk_narrative : 2-3 sentence AI risk note for Slide 6; None = omitted

    Returns
    -------
    BytesIO — ready to pass to st.download_button(data=...)
    """
    prs = Presentation()
    prs.slide_width  = _W
    prs.slide_height = _H

    # Compute projection if not provided
    if projection_df is None:
        projection_df = project_next_quarter(enriched_df)

    _slide_title(prs, enriched_df, period, tone)
    _slide_kpis(prs, enriched_df, period)
    _slide_waterfall(prs, waterfall_df, period)
    _slide_variances_table(prs, enriched_df, period)
    _slide_commentary(prs, commentary, tone, period)
    _slide_forward_look(prs, enriched_df, projection_df, risk_narrative, period)

    buf = BytesIO()
    prs.save(buf)
    buf.seek(0)
    return buf


# ── Slide builders ────────────────────────────────────────────────────────────

def _slide_title(
    prs: Presentation,
    enriched_df: pd.DataFrame,
    period: str,
    tone: str,
) -> None:
    """
    Slide 1 — Title.

    Dark (#0F172A) background.  Vertical teal accent bar on the left.
    Main title in white, period + tone as subtitle, headline metrics as a
    one-liner, timestamp and confidentiality notice at the bottom.
    """
    sl = _add_slide(prs)
    sl.background.fill.solid()
    sl.background.fill.fore_color.rgb = _rgb(_C["dark"])

    # Left teal accent bar — full height, 0.18" wide
    _rect(sl, 0, 0, 0.18, 7.5, fill=_C["teal"], line=None)

    # Main title
    _txb(sl, "FP&A Variance Copilot",
         0.42, 1.70, 12.0, 0.95,
         size=36, bold=True, color=_C["white"])

    # Subtitle: period · tone
    _txb(sl, f"{period}   ·   {tone}",
         0.42, 2.80, 10.0, 0.60,
         size=18, color=_C["s400"])

    # Headline metrics line
    total_budget = enriched_df["Budget"].sum()
    total_actual = enriched_df["Actual"].sum()
    net_var      = total_actual - total_budget
    sign         = "+" if net_var >= 0 else ""
    _txb(
        sl,
        f"Budget  {_d(total_budget, compact=True)}   ·   "
        f"Actual  {_d(total_actual, compact=True)}   ·   "
        f"Net Variance  {sign}{_d(net_var, compact=True)}",
        0.42, 3.65, 12.0, 0.50,
        size=13, color=_C["s300"],
    )

    # Bottom separator line
    _rect(sl, 0.42, 6.45, 12.5, 0.02, fill=_C["s700"], line=None)

    # Timestamp (left)
    ts = datetime.now().strftime("%d %b %Y  %H:%M")
    _txb(sl, f"Generated  {ts}",
         0.42, 6.65, 6.0, 0.35,
         size=9, color=_C["s600"])

    # Confidentiality (right)
    _txb(sl, "Confidential — Internal Use Only",
         6.5, 6.65, 6.33, 0.35,
         size=9, color=_C["s600"], align=PP_ALIGN.RIGHT)

    # Byline
    _txb(sl, "Built by Priyanka Chandramohan",
         0.42, 7.10, 8.0, 0.28,
         size=8, color=_C["s700"])


def _slide_kpis(
    prs: Presentation,
    enriched_df: pd.DataFrame,
    period: str,
) -> None:
    """
    Slide 2 — Executive KPIs.

    Four teal-accented card boxes on a light (#F8FAFC) background.
    Net Variance value is green or red depending on direction.
    Material Items value is red if more than half are unfavorable.
    """
    sl = _add_slide(prs)
    sl.background.fill.solid()
    sl.background.fill.fore_color.rgb = _rgb(_C["s50"])

    _slide_title_bar(sl, f"Executive Summary   ·   {period}")

    # Metrics
    total_budget   = enriched_df["Budget"].sum()
    total_actual   = enriched_df["Actual"].sum()
    net_var        = total_actual - total_budget
    material_mask  = enriched_df["Material"]
    n_material     = int(material_mask.sum())
    n_unfav        = int((material_mask & ~enriched_df["Favorable"]).sum())

    sign      = "+" if net_var >= 0 else ""
    net_color = _C["green"] if net_var >= 0 else _C["red"]
    mat_color = _C["red"] if n_unfav > n_material / 2 else _C["s800"]

    # 4 boxes: x positions computed from fixed widths
    BOX_W  = 2.90   # inches
    BOX_H  = 1.68
    BOX_Y  = 1.42
    GAP    = 0.22
    STARTS = [_ML + i * (BOX_W + GAP) for i in range(4)]

    cards = [
        (STARTS[0], "TOTAL BUDGET",   _d(total_budget, compact=True), _C["s800"], period),
        (STARTS[1], "TOTAL ACTUAL",   _d(total_actual, compact=True), _C["s800"], period),
        (STARTS[2], "NET VARIANCE",   f"{sign}{_d(net_var, compact=True)}", net_color, "vs. budget"),
        (STARTS[3], "MATERIAL ITEMS", str(n_material), mat_color, f"{n_unfav} unfavorable"),
    ]

    for x, label, value, val_color, subtitle in cards:
        _kpi_box(sl, x, BOX_Y, BOX_W, BOX_H, label, value, subtitle, val_color)

    # Explanatory note below boxes
    _txb(
        sl,
        f"Material = variance exceeds 5% of budget or $50K absolute   ·   "
        f"{n_material} items flagged across {len(enriched_df['Category'].unique())} categories",
        _ML, 3.35, _CW, 0.35,
        size=9, color=_C["s400"],
    )


def _slide_waterfall(
    prs: Presentation,
    waterfall_df: pd.DataFrame,
    period: str,
) -> None:
    """
    Slide 3 — Waterfall chart.

    Renders the Plotly waterfall as a PNG via kaleido and embeds it full-width.
    Falls back to a text notice if kaleido is not installed.
    """
    sl = _add_slide(prs)
    _slide_title_bar(sl, f"Budget-to-Actual Bridge   ·   {period}")

    fig = plot_waterfall(waterfall_df, title="")
    img = _chart_png(fig, width=1240, height=560)
    if img:
        sl.shapes.add_picture(
            img,
            Inches(_ML), Inches(_CT),
            Inches(_CW), Inches(5.85),
        )
    else:
        _kaleido_notice(sl)


def _slide_variances_table(
    prs: Presentation,
    enriched_df: pd.DataFrame,
    period: str,
) -> None:
    """
    Slide 4 — Material variances table.

    Sorted by absolute dollar impact.  Header row in dark slate with white text.
    Alternating row shading (#F8FAFC on even rows).  Dollar and % columns are
    right-aligned.  Severity column uses color coding: red (Critical/Major),
    amber (Moderate), slate (Minor).
    """
    sl = _add_slide(prs)
    _slide_title_bar(sl, f"Material Variances   ·   {period}")

    material   = get_material_items(enriched_df)
    COL_NAMES  = ["Line Item", "Category", "Budget", "Actual",
                  "Variance ($)", "Variance (%)", "Severity"]
    COL_WIDTHS = [3.40, 1.85, 1.35, 1.35, 1.35, 1.10, 1.03]   # inches, sum ≈ 11.43"
    RIGHT_COLS = {"Budget", "Actual", "Variance ($)", "Variance (%)"}

    SEV_COLORS = {
        "Critical": _C["red"],
        "Major":    _C["red"],
        "Moderate": _C["amber"],
        "Minor":    _C["s500"],
    }

    # Cap at 12 rows to stay on one slide; header counts as row 0
    rows_data = material[COL_NAMES].head(12)
    n_rows    = len(rows_data) + 1   # +1 for header

    # Row height scales so table fills the content area comfortably
    row_h_in  = min(0.42, (_CH - 0.10) / n_rows)
    tbl_h_in  = row_h_in * n_rows

    tbl = sl.shapes.add_table(
        n_rows, len(COL_NAMES),
        Inches(_ML), Inches(_CT),
        Inches(sum(COL_WIDTHS)), Inches(tbl_h_in),
    ).table

    # Set column widths
    for ci, w in enumerate(COL_WIDTHS):
        tbl.columns[ci].width = Inches(w)

    # Header row
    for ci, col_name in enumerate(COL_NAMES):
        cell = tbl.cell(0, ci)
        _tbl_cell(
            cell, col_name,
            bg=_C["s800"], fg=_C["white"],
            size=9, bold=True,
            align=PP_ALIGN.RIGHT if col_name in RIGHT_COLS else PP_ALIGN.LEFT,
        )

    # Data rows
    for ri, (_, row) in enumerate(rows_data.iterrows(), start=1):
        even = (ri % 2 == 0)
        bg   = _C["s50"] if even else _C["white"]

        for ci, col_name in enumerate(COL_NAMES):
            val = row[col_name]

            if col_name in ("Budget", "Actual", "Variance ($)"):
                text = _d(float(val))
            elif col_name == "Variance (%)":
                text = _p(float(val))
            else:
                text = str(val) if pd.notna(val) else "—"

            sev_color = (
                SEV_COLORS.get(str(val), _C["s700"])
                if col_name == "Severity" else _C["s700"]
            )
            is_fav    = bool(row.get("Favorable", True))
            var_color = (_C["green"] if is_fav else _C["red"]) if col_name == "Variance ($)" else sev_color

            _tbl_cell(
                tbl.cell(ri, ci), text,
                bg=bg, fg=var_color,
                size=9, bold=False,
                align=PP_ALIGN.RIGHT if col_name in RIGHT_COLS else PP_ALIGN.LEFT,
            )

    # Footer note
    if len(material) > 12:
        _txb(
            sl,
            f"Showing 12 of {len(material)} material items — sorted by absolute variance impact.",
            _ML, _CT + tbl_h_in + 0.12, _CW, 0.28,
            size=8, color=_C["s400"],
        )


def _slide_commentary(
    prs: Presentation,
    commentary: str | None,
    tone: str,
    period: str,
) -> None:
    """
    Slide 5 — Commentary.

    Left teal accent bar.  Text cleaned of markdown formatting.
    ALL-CAPS section headers are rendered in bold.
    Title includes the active tone label so readers know the analytical framing.
    """
    sl = _add_slide(prs)
    _slide_title_bar(sl, f"Commentary   ·   {tone}   ·   {period}")

    # Left teal accent bar
    _rect(sl, _ML, _CT, 0.06, _CH, fill=_C["teal"], line=None)

    if not commentary:
        _txb(
            sl,
            "Commentary not yet generated.  Click 'Generate Commentary' in the app "
            "and re-download to include the AI narrative.",
            _ML + 0.18, _CT + 0.20, _CW - 0.18, 1.0,
            size=11, color=_C["s400"],
        )
        return

    cleaned_paras = _clean_commentary(commentary)

    txb = sl.shapes.add_textbox(
        Inches(_ML + 0.18), Inches(_CT + 0.10),
        Inches(_CW - 0.22), Inches(_CH - 0.15),
    )
    tf           = txb.text_frame
    tf.word_wrap = True

    first = True
    for text, is_section_header in cleaned_paras:
        p    = tf.paragraphs[0] if first else tf.add_paragraph()
        first = False
        p.alignment = PP_ALIGN.LEFT

        # Add a small vertical space before section headers
        if is_section_header:
            p.space_before = Pt(6)

        run            = p.add_run()
        run.text       = text
        run.font.name  = "Calibri"
        run.font.size  = Pt(9.5)
        run.font.bold  = is_section_header
        run.font.color.rgb = _rgb(_C["s800"] if is_section_header else _C["s700"])


def _slide_forward_look(
    prs: Presentation,
    enriched_df: pd.DataFrame,
    projection_df: pd.DataFrame,
    risk_narrative: str | None,
    period: str,
) -> None:
    """
    Slide 6 — Forward Look.

    Two-zone layout: left two-thirds holds the projection table, right third
    holds the summary stats box.  Risk narrative appears below the table.

    At-risk items in the table are highlighted with red text in the Risk Flag column.
    """
    next_q = next_quarter_label(period)
    sl     = _add_slide(prs)
    _slide_title_bar(sl, f"Forward Look   ·   {period}  →  {next_q}")

    summary = summarize_projection(projection_df, period=period, next_q_label=next_q)

    # ── Projection table (left zone, width ≈ 8.5") ───────────────────────────
    material_proj = projection_df[projection_df["Material"]].head(10)
    PROJ_COLS  = ["Line Item", "Category",
                  "Current Var ($)", "Projected Var ($)", "Projected Var (%)", "Risk"]
    PROJ_WIDTHS = [3.10, 1.75, 1.45, 1.45, 1.30, 1.05]   # sum = 10.1"
    RIGHT_PROJ = {"Current Var ($)", "Projected Var ($)", "Projected Var (%)"}

    n_rows  = len(material_proj) + 1
    tbl_h   = min(_CH - 1.0, n_rows * 0.40 + 0.05)

    tbl = sl.shapes.add_table(
        n_rows, len(PROJ_COLS),
        Inches(_ML), Inches(_CT),
        Inches(sum(PROJ_WIDTHS)), Inches(tbl_h),
    ).table

    for ci, w in enumerate(PROJ_WIDTHS):
        tbl.columns[ci].width = Inches(w)

    # Header
    for ci, col_name in enumerate(PROJ_COLS):
        _tbl_cell(
            tbl.cell(0, ci), col_name,
            bg=_C["s800"], fg=_C["white"],
            size=8, bold=True,
            align=PP_ALIGN.RIGHT if col_name in RIGHT_PROJ else PP_ALIGN.LEFT,
        )

    # Data rows
    for ri, (_, row) in enumerate(material_proj.iterrows(), start=1):
        even    = (ri % 2 == 0)
        at_risk = bool(row["At Risk"])
        bg      = _C["s50"] if even else _C["white"]

        col_values = {
            "Line Item":          str(row["Line Item"]),
            "Category":           str(row["Category"]),
            "Current Var ($)":    _d(float(row["Variance ($)"])),
            "Projected Var ($)":  _d(float(row["Projected Variance ($)"])),
            "Projected Var (%)":  _p(float(row["Projected Variance (%)"])),
            "Risk":               "⚠ At Risk" if at_risk else "—",
        }

        for ci, col_name in enumerate(PROJ_COLS):
            risk_fg = _C["red"] if (at_risk and col_name == "Risk") else _C["s700"]
            _tbl_cell(
                tbl.cell(ri, ci), col_values[col_name],
                bg=bg, fg=risk_fg,
                size=8, bold=(at_risk and col_name == "Risk"),
                align=PP_ALIGN.RIGHT if col_name in RIGHT_PROJ else PP_ALIGN.LEFT,
            )

    # ── Summary stats box (right zone, float card) ────────────────────────────
    card_x = _ML + sum(PROJ_WIDTHS) + 0.25
    card_w = max(0.5, 13.33 - _MR - card_x)
    if card_w >= 1.5:
        proj_var   = summary["projected_net_variance"]
        proj_pct   = summary["projected_net_variance_pct"]
        n_risk     = summary["n_at_risk"]
        sign       = "+" if proj_var >= 0 else ""
        var_color  = _C["green"] if proj_var >= 0 else _C["red"]

        _rect(sl, card_x, _CT, card_w, _CH * 0.55, fill=_C["s50"], line=_C["s200"])

        _txb(sl, "Q+1 PROJECTION", card_x + 0.12, _CT + 0.14, card_w - 0.18, 0.28,
             size=8, bold=True, color=_C["s400"])
        _txb(sl, f"{sign}{_d(proj_var, compact=True)}",
             card_x + 0.12, _CT + 0.48, card_w - 0.18, 0.52,
             size=20, bold=True, color=var_color)
        _txb(sl, f"{sign}{proj_pct:.1f}%  vs. budget",
             card_x + 0.12, _CT + 1.08, card_w - 0.18, 0.30,
             size=9, color=_C["s500"])

        _rect(sl, card_x, _CT + 1.52, card_w, 0.015, fill=_C["s200"], line=None)

        risk_color = _C["red"] if n_risk > 0 else _C["green"]
        _txb(sl, "AT RISK", card_x + 0.12, _CT + 1.62, card_w - 0.18, 0.25,
             size=8, bold=True, color=_C["s400"])
        _txb(sl, str(n_risk), card_x + 0.12, _CT + 1.90, card_w - 0.18, 0.45,
             size=20, bold=True, color=risk_color)
        _txb(sl, "items flagged", card_x + 0.12, _CT + 2.38, card_w - 0.18, 0.25,
             size=9, color=_C["s500"])

    # ── Risk narrative ────────────────────────────────────────────────────────
    narrative_y = _CT + tbl_h + 0.20
    if risk_narrative and narrative_y + 0.60 < 7.3:
        # Red left accent bar for risk narrative
        _rect(sl, _ML, narrative_y, 0.05, 0.65, fill=_C["red"], line=None)
        safe_narrative = _clean_text(risk_narrative)
        _txb(
            sl, safe_narrative,
            _ML + 0.15, narrative_y + 0.05,
            sum(PROJ_WIDTHS) - 0.10, 0.60,
            size=9, color=_C["s700"],
        )
    elif narrative_y + 0.40 < 7.3:
        _txb(
            sl,
            "Generate commentary with an API key to include AI risk narrative.",
            _ML, narrative_y, sum(PROJ_WIDTHS), 0.35,
            size=9, color=_C["s400"],
        )


# ── Low-level helpers ─────────────────────────────────────────────────────────

def _add_slide(prs: Presentation):
    """Add a fully blank slide (layout index 6) and return it."""
    blank = prs.slide_layouts[6]
    return prs.slides.add_slide(blank)


def _slide_title_bar(slide, text: str) -> None:
    """
    Add the standard content-slide title text box.

    No accent lines under titles — just the text, positioned at the top of
    the slide with a consistent style across all content slides.
    """
    _txb(
        slide, text,
        _ML, 0.28, _CW, 0.60,
        size=15, bold=True, color=_C["s800"],
    )


def _txb(
    slide,
    text: str,
    left: float, top: float, width: float, height: float,
    size: int = 12,
    bold: bool = False,
    color: str | None = None,
    align: int = PP_ALIGN.LEFT,
) -> None:
    """
    Add a text box with consistent Calibri formatting.

    All position/size arguments are in inches.
    """
    color = color or _C["s800"]
    txb   = slide.shapes.add_textbox(
        Inches(left), Inches(top), Inches(width), Inches(height)
    )
    tf           = txb.text_frame
    tf.word_wrap = True
    para         = tf.paragraphs[0]
    para.alignment = align
    run            = para.add_run()
    run.text       = text
    run.font.size  = Pt(size)
    run.font.bold  = bold
    run.font.color.rgb = _rgb(color)
    run.font.name  = "Calibri"


def _rect(
    slide,
    left: float, top: float, width: float, height: float,
    fill: str | None = None,
    line: str | None = None,
) -> None:
    """
    Add a plain rectangle shape.

    fill / line: hex color string or None (None = transparent / no line).
    All dimensions in inches.
    """
    shape = slide.shapes.add_shape(
        1, Inches(left), Inches(top), Inches(width), Inches(height)
    )
    if fill:
        shape.fill.solid()
        shape.fill.fore_color.rgb = _rgb(fill)
    else:
        shape.fill.background()

    if line:
        shape.line.color.rgb = _rgb(line)
        shape.line.width     = Pt(0.75)
    else:
        shape.line.fill.background()


def _kpi_box(
    slide,
    left: float, top: float, width: float, height: float,
    label: str, value: str, subtitle: str,
    value_color: str,
) -> None:
    """
    Draw a single KPI card: white background, teal top strip, label/value/subtitle.

    The teal strip (0.05" tall) gives each card a brand-consistent accent without
    competing with the data.  The label uses all-caps at 8pt, the value is large
    and colored, the subtitle is muted.
    """
    # White card background
    _rect(slide, left, top, width, height, fill=_C["white"], line=_C["s200"])

    # Teal top strip
    _rect(slide, left, top, width, 0.055, fill=_C["teal"], line=None)

    # Label (all-caps, muted)
    _txb(slide, label,
         left + 0.14, top + 0.12, width - 0.20, 0.28,
         size=8, bold=True, color=_C["s400"])

    # Value (large, colored)
    _txb(slide, value,
         left + 0.14, top + 0.45, width - 0.20, 0.58,
         size=22, bold=True, color=value_color)

    # Subtitle (small, muted)
    _txb(slide, subtitle,
         left + 0.14, top + 1.12, width - 0.20, 0.28,
         size=8, color=_C["s400"])


def _tbl_cell(
    cell,
    text: str,
    bg: str,
    fg: str,
    size: int = 9,
    bold: bool = False,
    align: int = PP_ALIGN.LEFT,
) -> None:
    """
    Set the background color, text, and font of a python-pptx table cell.

    Centralises all cell formatting so table builders stay readable.
    """
    cell.fill.solid()
    cell.fill.fore_color.rgb = _rgb(bg)

    tf = cell.text_frame
    tf.word_wrap = False
    para         = tf.paragraphs[0]
    para.alignment = align

    # Clear any existing runs
    for run in para.runs:
        run.text = ""

    if para.runs:
        run = para.runs[0]
    else:
        run = para.add_run()

    run.text       = text
    run.font.name  = "Calibri"
    run.font.size  = Pt(size)
    run.font.bold  = bold
    run.font.color.rgb = _rgb(fg)


def _chart_png(fig, width: int = 1200, height: int = 560) -> BytesIO | None:
    """
    Render a Plotly figure to a PNG BytesIO buffer via kaleido.

    Returns None if kaleido is not installed — callers fall back to a text
    notice rather than crashing.  The scale=2 argument produces a 2×
    resolution image that looks crisp on high-DPI displays and in PDF export.
    """
    try:
        raw = fig.to_image(format="png", width=width, height=height, scale=2)
        buf = BytesIO(raw)
        buf.seek(0)
        return buf
    except Exception:
        return None


def _kaleido_notice(slide) -> None:
    """Render a placeholder when kaleido is not available."""
    _txb(
        slide,
        "Chart image requires kaleido  →  pip install kaleido",
        _ML, 3.20, _CW, 0.60,
        size=11, color=_C["s400"], align=PP_ALIGN.CENTER,
    )


def _clean_commentary(text: str) -> list[tuple[str, bool]]:
    """
    Strip markdown formatting and return a list of (paragraph_text, is_bold) tuples.

    Rules applied
    -------------
    - ``**text**`` and ``*text*`` → plain text
    - ``# heading`` → plain text  (marked bold if starts with # or is ALL CAPS)
    - ``---`` separator lines → skipped
    - Blank lines → skipped (paragraph spacing is handled by space_before on headers)
    - Lines that are ALL CAPS or start with ``#`` → rendered bold as section headers
    """
    text   = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text   = re.sub(r"\*(.+?)\*",     r"\1", text)
    text   = re.sub(r"^#{1,4}\s+",    "",    text, flags=re.MULTILINE)

    result = []
    for line in text.splitlines():
        line = line.rstrip()
        if not line or re.match(r"^-{3,}$", line):
            continue
        # Section header heuristic: all-caps word run ≥ 3 chars, or starts capital-colon
        stripped = line.strip()
        is_header = bool(
            re.match(r"^[A-Z][A-Z\s&/·\-:]{2,}$", stripped)      # ALL CAPS line
            or re.match(r"^[A-Z][A-Za-z\s]+:\s*$", stripped)      # "Title:" pattern
        )
        result.append((stripped, is_header))

    return result


def _clean_text(text: str) -> str:
    """Strip markdown for single-line text boxes (narrative, subtitle)."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\*(.+?)\*",     r"\1", text)
    text = re.sub(r"^#{1,4}\s+",    "",    text, flags=re.MULTILINE)
    return text.strip()


def _rgb(hex_color: str) -> RGBColor:
    """Convert a 6-char CSS hex string to a python-pptx RGBColor."""
    h = hex_color.lstrip("#")
    return RGBColor(int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))


def _d(value: float, compact: bool = False, sign: bool = False) -> str:
    """Format *value* as a currency string."""
    if pd.isna(value):
        return "—"
    prefix = ("+" if value >= 0 else "") if sign else ""
    neg    = "-" if value < 0 else ""
    abs_v  = abs(value)
    if compact:
        if abs_v >= 1_000_000:
            return f"{prefix}{neg}${abs_v / 1_000_000:.1f}M"
        if abs_v >= 1_000:
            return f"{prefix}{neg}${abs_v / 1_000:.0f}K"
    return f"{prefix}${value:,.0f}"


def _p(value: float) -> str:
    """Format *value* as a signed percentage string."""
    if pd.isna(value):
        return "—"
    return f"{value:+.1f}%"
